/**
 * Builds the complete message that gets transmitted.
 *
 * WHY THIS APPLICATION BUILDS THE WHOLE RFC 5322 MESSAGE, RATHER THAN HANDING
 * OVER FIELDS FOR THE SENDER TO ASSEMBLE.
 *
 * The original plan was for n8n's built-in Send Email node to compose the
 * reply from `to`/`subject`/`body`. Checked against n8n's own source and
 * documentation, that node cannot do what threaded replies require:
 *
 *   - It exposes exactly seven options — `appendAttribution`, `attachments`,
 *     `fileAttachments`, `ccEmail`, `bccEmail`, `allowUnauthorizedCerts`,
 *     `replyTo` — and hands nodemailer a hard-coded object built only from
 *     those. No custom headers can reach the message.
 *   - n8n's documentation states the limitation outright: the node "does not
 *     support setting headers like `In-Reply-To` and `References`, which are
 *     required for email threading. As a result, each email is treated as a
 *     new conversation."
 *   - It does not expose nodemailer's `envelope`, so `MAIL FROM` is always
 *     derived from the `From:` header — which rules out a per-message VERP
 *     return path through that node.
 *
 * Designing around those limits would have meant shipping replies that do not
 * thread in the recipient's client and bounces that correlate to nothing. So
 * the boundary moved rather than the requirement: this application produces a
 * finished message plus an explicit envelope, and the transmitter's only job is
 * to issue `MAIL FROM`, `RCPT TO` and `DATA`. That also makes the CRM side
 * independent of which transmitter is used — nodemailer's `raw`, a shim, or
 * anything else — which is the property worth having.
 *
 * THIS STILL DOES NOT SEND. It returns a string. Nothing in this repository
 * opens a socket, and the Email Worker cannot originate arbitrary mail either
 * (`reply()` may only answer the message currently being handled, once, and
 * only when it passed DMARC).
 */

import { encodeHeaderValue, formatAddress, formatDate, wrapBody } from '../../lead-engine/mail/eml.js'
import { PRIMARY_ADDRESS } from '../config.js'

/**
 * Removes anything that could inject a second header.
 *
 * A subject or display name that came from an inbound message is
 * attacker-controlled, and a bare CR or LF in it appends headers of the
 * sender's choosing — `Bcc:` being the obvious one. `encodeHeaderValue`
 * already collapses newlines for non-ASCII values, but an ASCII-only value
 * takes the fast path and would pass straight through.
 *
 * @param {string} value
 */
function headerSafe(value) {
  return String(value ?? '').replace(/[\r\n\u2028\u2029]+/g, ' ').trim()
}

/**
 * Assembles a plain-text message.
 *
 * Plain text only, and that is a decision rather than a limitation. A reply to
 * a prospect is correspondence; multipart/alternative would double the size,
 * add a rendering surface, and give a spam filter more to dislike from a domain
 * with no sending history.
 *
 * @param {{
 *   to: { email: string, name?: string|null },
 *   from?: { email: string, name?: string|null },
 *   subject: string,
 *   bodyText: string,
 *   messageId: string,
 *   inReplyTo?: string|null,
 *   references?: string[]|null,
 *   replyTo?: string|null,
 *   date?: Date,
 * }} input
 * @returns {string}
 */
export function buildOutboundMessage(input) {
  const date = input.date instanceof Date ? input.date : new Date()
  const from = input.from?.email ? input.from : { email: PRIMARY_ADDRESS, name: 'DevLab Studios' }

  const headers = [
    `From: ${formatAddress({ email: from.email, name: headerSafe(from.name) })}`,
    `To: ${formatAddress({ email: input.to.email, name: headerSafe(input.to.name) })}`,
    `Subject: ${encodeHeaderValue(headerSafe(input.subject))}`,
    `Date: ${formatDate(date)}`,
    // Generated by us, never left to the transmitter. It is the identifier a
    // DSN echoes back, and it is how the bounce path finds the draft without
    // depending on the envelope sender surviving. See domain/messageId.js.
    `Message-ID: <${input.messageId}>`,
  ]

  if (input.replyTo) headers.push(`Reply-To: ${formatAddress({ email: input.replyTo })}`)

  if (input.inReplyTo) {
    headers.push(`In-Reply-To: <${input.inReplyTo}>`)
  }

  const chain = (input.references ?? []).filter(Boolean)
  if (chain.length > 0) {
    // Folded onto continuation lines: a long References header routinely
    // exceeds the 998-octet line limit, and a receiver that enforces it rejects
    // the message outright.
    headers.push(`References: ${chain.map((id) => `<${id}>`).join('\r\n ')}`)
  }

  headers.push('MIME-Version: 1.0')
  headers.push('Content-Type: text/plain; charset=utf-8')
  headers.push('Content-Transfer-Encoding: 8bit')

  return `${headers.join('\r\n')}\r\n\r\n${wrapBody(input.bodyText)}\r\n`
}

/**
 * The reply subject, adding `Re:` exactly once.
 *
 * `Re: Re: Re:` is what happens when each side prepends without checking, and
 * it is the visible symptom of a thread nobody is tracking properly.
 *
 * @param {string} subject
 */
export function replySubject(subject) {
  const text = headerSafe(subject) || '(no subject)'
  return /^re\s*:/i.test(text) ? text : `Re: ${text}`
}
