-- Lead Intelligence Engine seed.
-- Generated by scripts/lead-engine/seed.mjs. Safe to re-run: every
-- statement is INSERT OR IGNORE, so applying it twice changes nothing.
--
-- SOURCES ARE REGISTERED BUT DISABLED AND UNREVIEWED.
-- THE CAMPAIGN IS A DRAFT WITH ITS SCHEDULE DISARMED.
-- Nothing here causes the engine to discover, crawl, or contact anyone.

INSERT OR IGNORE INTO lead_sources
  (id, name, slug, type, base_url, enabled, automation_allowed, crawl_allowed,
   policy_status, policy_notes, parser_version, created_at, updated_at)
VALUES ('daa2d7be-4b63-46ad-809e-d927b85ac537', 'OpenStreetMap (Overpass API)', 'osm-overpass', 'osm_overpass', 'https://overpass-api.de/api/interpreter',
        0, 0, 0, 'unreviewed', 'Data is ODbL-licensed and openly available. Before enabling, confirm the current Overpass API usage policy (https://operations.osmfoundation.org/policies/api/) and that our request volume and rate are within it. The adapter is sequential and bounded by USAGE_LIMITS.overpass_requests, but the ceiling is ours to justify. Attribution: OSM data must be credited where it is displayed publicly. It is not displayed publicly here — it is internal research evidence only.', 1, '2026-09-18T07:02:18.075Z', '2026-09-18T07:02:18.075Z');

INSERT OR IGNORE INTO lead_sources
  (id, name, slug, type, base_url, enabled, automation_allowed, crawl_allowed,
   policy_status, policy_notes, parser_version, created_at, updated_at)
VALUES ('9864b8d8-0116-4157-b3db-2d9f44f1f29e', 'Brave Search API', 'brave-search', 'search_api', 'https://api.search.brave.com/res/v1/web/search',
        0, 0, 0, 'unreviewed', 'A paid, documented API with its own terms. Before enabling, confirm the plan permits this use and note the request quota. The adapter is entirely optional: with no API key the engine works and simply discovers fewer candidates. Snippets are never forwarded to Workers AI — Brave is used for domain discovery only.', 1, '2026-09-18T07:02:18.075Z', '2026-09-18T07:02:18.075Z');

INSERT OR IGNORE INTO lead_sources
  (id, name, slug, type, base_url, enabled, automation_allowed, crawl_allowed,
   policy_status, policy_notes, parser_version, created_at, updated_at)
VALUES ('bcfd73aa-26bd-4c25-991a-75f42db05bf4', 'Manual import (CSV / domain list)', 'manual-import', 'manual_import', NULL,
        0, 0, 0, 'unreviewed', 'Candidates an operator pastes in by hand. No third-party terms apply to the import itself, but the SOURCE of the list does matter: do not import a purchased list. Imported rows go through the same normalization, deduplication and compliance gate as anything an automated adapter found.', 1, '2026-09-18T07:02:18.075Z', '2026-09-18T07:02:18.075Z');

INSERT OR IGNORE INTO lead_campaigns
  (id, name, slug, description, status, country_code, config_json,
   max_candidates, max_ai_reviews, schedule_enabled, schedule_cron,
   created_by, created_at, updated_at)
VALUES ('61ffcfa9-468d-4184-9b3c-f04cc05c33e7', 'US Property Management — Dry Run', 'us-property-management-dry-run', 'The first production-like test of the Lead Intelligence Engine. Seeded as a DRAFT with its schedule disarmed: activating it and arming the schedule are separate, deliberate actions. The first run is expected to stop at READY_TO_CONTACT with no email sent, so that business quality, crawler accuracy, signal accuracy, score quality, AI opportunity quality and contact provenance can all be inspected before anyone is contacted.',
        'draft', 'US', '{"industryLabel":"Property management","targetIndustries":["property management","property manager","rental management","hoa management","community association management","residential property management"],"serviceTerms":["tenant screening","rent collection","maintenance coordination","lease renewal","property marketing","eviction","inspection","owner statement","hoa management","vendor management","move-in","move-out"],"disqualifyingKeywords":["we buy houses","cash for your home","mortgage broker","title insurance","real estate school","property management software","property management platform","franchise opportunity"],"metros":["Austin","Dallas","Tampa","Phoenix","Charlotte"],"overpass":{"areas":[{"name":"Austin, TX","bbox":[30.1,-97.94,30.52,-97.56]},{"name":"Dallas, TX","bbox":[32.62,-96.99,32.99,-96.6]},{"name":"Tampa, FL","bbox":[27.86,-82.58,28.08,-82.34]},{"name":"Phoenix, AZ","bbox":[33.29,-112.32,33.71,-111.92]},{"name":"Charlotte, NC","bbox":[35.1,-80.95,35.39,-80.68]}],"tags":[{"key":"office","value":"estate_agent"},{"key":"office","value":"property_management"},{"key":"shop","value":"estate_agent"}]},"brave":{"queries":["\"property management company\" \"Austin Texas\"","\"rental property management\" \"Dallas Texas\"","\"HOA management company\" \"Tampa Florida\"","\"property management\" \"Phoenix Arizona\"","\"property management company\" \"Charlotte North Carolina\""],"country":"US","count":20}}',
        100, 40, 0, NULL,
        'seed-script', '2026-09-18T07:02:18.075Z', '2026-09-18T07:02:18.075Z');

INSERT OR IGNORE INTO lead_settings (key, value_json, is_secret, updated_by, updated_at)
VALUES ('business.identity', '{"legalName":"DevLab Studios","senderName":"","senderEmail":"","postalAddress":"","city":"","region":"","postalCode":"","countryCode":"","website":"https://www.devlabstudios.com"}', 0, 'seed-script', '2026-09-18T07:02:18.075Z');

-- Next steps (all manual, all in the admin):
--   1. Read each source's terms. Record the review on Lead CRM > Sources.
--   2. Enable the sources you approved, and allow automation on them.
--   3. Fill in business.identity on Lead CRM > CRM Settings. The US
--      compliance profile holds every lead until the postal address is set.
--   4. Set LEAD_ENGINE_ENABLED / LEAD_DISCOVERY_ENABLED / LEAD_CRAWLER_ENABLED
--      / LEAD_AI_ENABLED as Worker vars.
--   5. Activate the campaign, then use "Dry run" before "Run discovery".
--   6. Leave LEAD_CAMPAIGN_SCHEDULES_ENABLED off until the dry run looks right.
-- See docs/lead-engine/dry-run.md.
