-- Lead Intelligence Engine seed.
-- Generated by scripts/lead-engine/seed.mjs. Safe to re-run: every
-- statement is INSERT OR IGNORE, so applying it twice changes nothing.
--
-- SOURCES ARE REGISTERED BUT DISABLED AND UNREVIEWED.
-- THE CAMPAIGN IS A DRAFT WITH ITS SCHEDULE DISARMED.
-- Nothing here causes the engine to discover, crawl, or contact anyone.

INSERT OR IGNORE INTO lead_sources
  (id, name, slug, type, base_url, enabled, automation_allowed, crawl_allowed,
   policy_status, policy_notes, parser_version, created_at, updated_at)
VALUES ('ebcaaf31-ed5e-4c8a-a3b0-b76adac13fe9', 'OpenStreetMap (Overpass API)', 'osm-overpass', 'osm_overpass', 'https://overpass-api.de/api/interpreter',
        0, 0, 0, 'unreviewed', 'Data is ODbL-licensed and openly available. Before enabling, review the current public instance guidance (https://wiki.openstreetmap.org/wiki/Overpass_API) and the policy of the exact endpoint configured. The main public instance directs regular commercial use to self-hosted or paid infrastructure. The adapter is sequential and bounded, but that does not itself grant permission to use an endpoint. Attribution: OSM data must be credited where it is displayed publicly. It is not displayed publicly here — it is internal research evidence only.', 1, '2026-09-18T15:24:20.702Z', '2026-09-18T15:24:20.702Z');

INSERT OR IGNORE INTO lead_sources
  (id, name, slug, type, base_url, enabled, automation_allowed, crawl_allowed,
   policy_status, policy_notes, parser_version, created_at, updated_at)
VALUES ('8e8c0ec6-ea84-41a9-acd1-5b021e8d8ad0', 'OpenStreetMap (Nominatim search)', 'osm-nominatim', 'search_api', 'https://nominatim.openstreetmap.org/search',
        0, 0, 0, 'unreviewed', 'Free, keyless, ODbL-licensed, over the same OpenStreetMap data as Overpass but asking a free-text question rather than a tag-and-bbox one. Before enabling, read the Nominatim Usage Policy (https://operations.osmfoundation.org/policies/nominatim/): it caps automated clients at ONE REQUEST PER SECOND as an absolute limit, requires an identifying User-Agent, and asks heavy users to self-host. The adapter enforces the interval with a real delay and keeps the per-run budget small, but that does not itself grant permission. Note on query phrasing: Nominatim resolves OSM special phrases, so "dentist Austin TX" and "law firm Houston" return results where "hvac contractor Phoenix" returns none. A zero-result query is reported per query so it can be rewritten. Attribution: OSM data must be credited where it is displayed publicly. It is not displayed publicly here — it is internal research evidence only.', 1, '2026-09-18T15:24:20.702Z', '2026-09-18T15:24:20.702Z');

INSERT OR IGNORE INTO lead_sources
  (id, name, slug, type, base_url, enabled, automation_allowed, crawl_allowed,
   policy_status, policy_notes, parser_version, created_at, updated_at)
VALUES ('9051fcb1-bd97-40d2-9dec-3d34584f76ef', 'Brave Search API', 'brave-search', 'search_api', 'https://api.search.brave.com/res/v1/web/search',
        0, 0, 0, 'unreviewed', 'A paid, documented API with its own terms. Before enabling, confirm the plan permits this use and note the request quota. The adapter is entirely optional: with no API key the engine works and simply discovers fewer candidates. Snippets are never forwarded to Workers AI — Brave is used for domain discovery only.', 1, '2026-09-18T15:24:20.702Z', '2026-09-18T15:24:20.702Z');

INSERT OR IGNORE INTO lead_sources
  (id, name, slug, type, base_url, enabled, automation_allowed, crawl_allowed,
   policy_status, policy_notes, parser_version, created_at, updated_at)
VALUES ('f301c301-b451-4eb4-8626-9806507d6e61', 'Manual import (CSV / domain list)', 'manual-import', 'manual_import', NULL,
        0, 0, 0, 'unreviewed', 'Candidates an operator pastes in by hand. No third-party terms apply to the import itself, but the SOURCE of the list does matter: do not import a purchased list. Imported rows go through the same normalization, deduplication and compliance gate as anything an automated adapter found.', 1, '2026-09-18T15:24:20.702Z', '2026-09-18T15:24:20.702Z');

INSERT OR IGNORE INTO lead_campaigns
  (id, name, slug, description, status, country_code, config_json,
   max_candidates, max_ai_reviews, schedule_enabled, schedule_cron,
   created_by, created_at, updated_at)
VALUES ('429cf6e5-13f5-4153-9dff-62ee38fb2e89', 'US Property Management — Dry Run', 'us-property-management-dry-run', 'The first production-like test of the Lead Intelligence Engine. Seeded as a DRAFT with its schedule disarmed: activating it and arming the schedule are separate, deliberate actions. The first run is expected to stop at READY_TO_CONTACT with no email sent, so that business quality, crawler accuracy, signal accuracy, score quality, AI opportunity quality and contact provenance can all be inspected before anyone is contacted.',
        'draft', 'US', '{"industryLabel":"Property management","targetIndustries":["property management","property manager","rental management","hoa management","community association management","residential property management"],"serviceTerms":["tenant screening","rent collection","maintenance coordination","lease renewal","property marketing","eviction","inspection","owner statement","hoa management","vendor management","move-in","move-out"],"disqualifyingKeywords":["we buy houses","cash for your home","mortgage broker","title insurance","real estate school","property management software","property management platform","franchise opportunity"],"metros":["Austin","Dallas","Tampa","Phoenix","Charlotte"],"overpass":{"areas":[{"name":"Austin, TX","bbox":[30.1,-97.94,30.52,-97.56]},{"name":"Dallas, TX","bbox":[32.62,-96.99,32.99,-96.6]},{"name":"Tampa, FL","bbox":[27.86,-82.58,28.08,-82.34]},{"name":"Phoenix, AZ","bbox":[33.29,-112.32,33.71,-111.92]},{"name":"Charlotte, NC","bbox":[35.1,-80.95,35.39,-80.68]}],"tags":[{"key":"office","value":"estate_agent"},{"key":"office","value":"property_management"},{"key":"shop","value":"estate_agent"}]},"nominatim":{"queries":["real estate Charlotte NC","real estate Austin TX"],"countryCodes":"us","limit":40},"brave":{"queries":["\"property management company\" \"Austin Texas\"","\"rental property management\" \"Dallas Texas\"","\"HOA management company\" \"Tampa Florida\"","\"property management\" \"Phoenix Arizona\"","\"property management company\" \"Charlotte North Carolina\""],"country":"US","count":20}}',
        100, 40, 0, NULL,
        'seed-script', '2026-09-18T15:24:20.702Z', '2026-09-18T15:24:20.702Z');

INSERT OR IGNORE INTO lead_campaigns
  (id, name, slug, description, status, country_code, config_json,
   max_candidates, max_ai_reviews, schedule_enabled, schedule_cron,
   created_by, created_at, updated_at)
VALUES ('998337cd-631b-4c9a-8084-b5aa5ac68eb7', 'US Legal & Professional Services', 'us-legal-professional-services', 'Cross-industry discovery for legal and professional services. Seeded as a DRAFT with its schedule disarmed, like Campaign 001: activating it and arming the schedule are separate, deliberate actions. Nominatim queries were measured against the live API before seeding and only phrasings that returned businesses with websites were kept.',
        'draft', 'US', '{"industryLabel":"Legal and professional services","targetIndustries":["law firm","attorney","legal services","litigation","law office"],"serviceTerms":["free consultation","case evaluation","client intake","retainer","practice areas"],"disqualifyingKeywords":["legal directory","find a lawyer","legal software","law school","bar association"],"metros":["Houston","Austin","Dallas","Charlotte"],"overpass":{"areas":[{"name":"Houston, TX","bbox":[29.6,-95.55,29.88,-95.2]},{"name":"Austin, TX","bbox":[30.1,-97.94,30.52,-97.56]},{"name":"Dallas, TX","bbox":[32.62,-96.99,32.99,-96.6]},{"name":"Charlotte, NC","bbox":[35.1,-80.95,35.39,-80.68]}],"tags":[{"key":"office","value":"lawyer"}]},"nominatim":{"queries":["law firm Houston","law firm Austin TX","law firm Dallas TX","law firm Charlotte NC"],"countryCodes":"us","limit":40}}',
        100, 40, 0, NULL,
        'seed-script', '2026-09-18T15:24:20.702Z', '2026-09-18T15:24:20.702Z');

INSERT OR IGNORE INTO lead_campaigns
  (id, name, slug, description, status, country_code, config_json,
   max_candidates, max_ai_reviews, schedule_enabled, schedule_cron,
   created_by, created_at, updated_at)
VALUES ('f3940e4b-7337-4b24-9622-89c24e18dc6e', 'US Dental & Medical Practices', 'us-dental-medical-practices', 'Cross-industry discovery for dental and medical practices. Seeded as a DRAFT with its schedule disarmed, like Campaign 001: activating it and arming the schedule are separate, deliberate actions. Nominatim queries were measured against the live API before seeding and only phrasings that returned businesses with websites were kept.',
        'draft', 'US', '{"industryLabel":"Dental and medical practices","targetIndustries":["dental practice","dentist","family medicine","clinic","medical practice"],"serviceTerms":["book an appointment","new patient","patient portal","insurance accepted","emergency visit"],"disqualifyingKeywords":["hospital system","medical school","practice management software","dental supplies"],"metros":["Austin","Dallas","Charlotte","Phoenix"],"overpass":{"areas":[{"name":"Austin, TX","bbox":[30.1,-97.94,30.52,-97.56]},{"name":"Dallas, TX","bbox":[32.62,-96.99,32.99,-96.6]},{"name":"Charlotte, NC","bbox":[35.1,-80.95,35.39,-80.68]},{"name":"Phoenix, AZ","bbox":[33.29,-112.32,33.71,-111.92]}],"tags":[{"key":"amenity","value":"dentist"},{"key":"amenity","value":"doctors"}]},"nominatim":{"queries":["dentist Austin TX","dentist Dallas TX","dentist Charlotte NC","doctors Phoenix AZ"],"countryCodes":"us","limit":40}}',
        100, 40, 0, NULL,
        'seed-script', '2026-09-18T15:24:20.702Z', '2026-09-18T15:24:20.702Z');

INSERT OR IGNORE INTO lead_campaigns
  (id, name, slug, description, status, country_code, config_json,
   max_candidates, max_ai_reviews, schedule_enabled, schedule_cron,
   created_by, created_at, updated_at)
VALUES ('9c2e985b-0caa-4a48-8f38-7aa62a967551', 'US Hospitality', 'us-hospitality', 'Cross-industry discovery for hotels and restaurants. Seeded as a DRAFT with its schedule disarmed, like Campaign 001: activating it and arming the schedule are separate, deliberate actions. Nominatim queries were measured against the live API before seeding and only phrasings that returned businesses with websites were kept.',
        'draft', 'US', '{"industryLabel":"Hotels and restaurants","targetIndustries":["hotel","inn","restaurant","bistro","hospitality"],"serviceTerms":["book a table","reservations","check availability","menu","private events"],"disqualifyingKeywords":["booking aggregator","restaurant directory","franchise opportunity","food delivery app"],"metros":["Charlotte","Austin","Dallas","Houston"],"overpass":{"areas":[{"name":"Charlotte, NC","bbox":[35.1,-80.95,35.39,-80.68]},{"name":"Austin, TX","bbox":[30.1,-97.94,30.52,-97.56]},{"name":"Dallas, TX","bbox":[32.62,-96.99,32.99,-96.6]},{"name":"Houston, TX","bbox":[29.6,-95.55,29.88,-95.2]}],"tags":[{"key":"tourism","value":"hotel"},{"key":"amenity","value":"restaurant"}]},"nominatim":{"queries":["hotel Charlotte NC","hotel Austin TX","restaurant Austin TX","restaurant Charlotte NC"],"countryCodes":"us","limit":40}}',
        100, 40, 0, NULL,
        'seed-script', '2026-09-18T15:24:20.702Z', '2026-09-18T15:24:20.702Z');

INSERT OR IGNORE INTO lead_campaigns
  (id, name, slug, description, status, country_code, config_json,
   max_candidates, max_ai_reviews, schedule_enabled, schedule_cron,
   created_by, created_at, updated_at)
VALUES ('bdc20e11-e3ff-4248-aab3-57363ba5d05d', 'US Local Services & Retail', 'us-local-services-retail', 'Cross-industry discovery for insurance, pharmacy and vehicle services. Seeded as a DRAFT with its schedule disarmed, like Campaign 001: activating it and arming the schedule are separate, deliberate actions. Nominatim queries were measured against the live API before seeding and only phrasings that returned businesses with websites were kept.',
        'draft', 'US', '{"industryLabel":"Insurance, pharmacy and vehicle services","targetIndustries":["insurance agency","pharmacy","auto repair","service centre","independent agent"],"serviceTerms":["get a quote","request an appointment","refill","schedule service","walk-ins welcome"],"disqualifyingKeywords":["comparison site","insurance marketplace","lead generation","franchise opportunity"],"metros":["Dallas","Austin","Charlotte","Phoenix"],"overpass":{"areas":[{"name":"Dallas, TX","bbox":[32.62,-96.99,32.99,-96.6]},{"name":"Austin, TX","bbox":[30.1,-97.94,30.52,-97.56]},{"name":"Charlotte, NC","bbox":[35.1,-80.95,35.39,-80.68]},{"name":"Phoenix, AZ","bbox":[33.29,-112.32,33.71,-111.92]}],"tags":[{"key":"office","value":"insurance"},{"key":"amenity","value":"pharmacy"},{"key":"shop","value":"car_repair"}]},"nominatim":{"queries":["insurance Dallas TX","pharmacy Austin TX","insurance Charlotte NC","car repair Dallas TX"],"countryCodes":"us","limit":40}}',
        100, 40, 0, NULL,
        'seed-script', '2026-09-18T15:24:20.702Z', '2026-09-18T15:24:20.702Z');

INSERT OR IGNORE INTO lead_settings (key, value_json, is_secret, updated_by, updated_at)
VALUES ('business.identity', '{"legalName":"DevLab Studios","senderName":"","senderEmail":"","postalAddress":"","city":"","region":"","postalCode":"","countryCode":"","website":"https://www.devlabstudios.com"}', 0, 'seed-script', '2026-09-18T15:24:20.702Z');

-- Next steps (all manual, all in the admin):
--   1. Read each source's terms. Record the review on Lead CRM > Sources.
--   2. Enable the sources you approved, and allow automation on them.
--   3. Fill in business.identity on Lead CRM > CRM Settings. The US
--      compliance profile holds every lead until the postal address is set.
--   4. Set LEAD_ENGINE_ENABLED / LEAD_DISCOVERY_ENABLED / LEAD_CRAWLER_ENABLED
--      / LEAD_AI_ENABLED as Worker vars.
--   5. Activate the campaign, then use "Dry run" before "Run discovery".
--   6. Leave LEAD_CAMPAIGN_SCHEDULES_ENABLED off until the dry run looks right.
-- See docs/lead-engine/dry-run.md.
